name: CI/CD - Nexus Bot Platform

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/${{ github.repository }}/backend
  IMAGE_FRONTEND: ghcr.io/${{ github.repository }}/frontend
  IMAGE_MANAGER: ghcr.io/${{ github.repository }}/bot-manager

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend
        run: docker build -t $IMAGE_BACKEND:latest backend/

      - name: Build frontend
        run: docker build -t $IMAGE_FRONTEND:latest frontend/

      - name: Build bot-manager
        run: docker build -t $IMAGE_MANAGER:latest bot-manager/

      - name: Push all images
        run: |
          docker push $IMAGE_BACKEND:latest
          docker push $IMAGE_FRONTEND:latest
          docker push $IMAGE_MANAGER:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy stack via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/nexus-bot-platform
            docker compose pull
            docker compose up -d --remove-orphans
